apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - image: todo-app
          env:
          - name: PORT
            value: "3001"
          name: todo-app
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
status: {}
