FROM oven/bun AS base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
# install with --production (exclude devDependencies)
FROM base AS install
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /temp/prod/node_modules node_modules
COPY . .

ENV NODE_ENV=production

RUN bun run build

FROM gcr.io/distroless/base AS release

WORKDIR /usr/src/app

COPY --from=prerelease /usr/src/app/dist/public public
COPY --from=prerelease /usr/src/app/dist/server server

ENV NODE_ENV=production

CMD ["./server"]

EXPOSE 3000/tcp
